vich_uploader:
    db_driver: orm
    mappings:
        images:
            uri_prefix: '%app.path.images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
