<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Community;
use AppBundle\Entity\Player;
use Doctrine\ORM\EntityRepository;

/**
 * CommunityRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityRepository extends EntityRepository
{
    /**
     * Check if a community name exists.
     *
     * @param string $name
     * @return bool
     */
    public function checkIfNameExists(string $name) : bool
    {

    }

    /**
     * Find community by exact name.
     *
     * @param string $name
     * @return Community
     * @throws NotFoundException If there is no communities with that name
     */
    public function findByName(string $name): Community
    {

    }

    /**
     * Get all public communities.
     *
     * If a player is passed, retrieve all public communities to which player is not a member.
     *
     * @param Player $player
     * @return Community[]
     */
    public function getAllPublicCommunities(Player $player = null) : array
    {

    }

    /**
     * Retrieve a random community.
     *
     * If a player is passed, retrieve random community to which player is not member.
     *
     * @param Player|null $player
     * @return Community
     */
    public function getRandomCommunity(Player $player = null): Community
    {

    }
}
