<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Community;
use AppBundle\Entity\Player;
use AppBundle\Legacy\Model\Exception\NotFoundException;
use AppBundle\Legacy\Util\General\ErrorCodes;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityRepository;

/**
 * CommunityRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityRepository extends EntityRepository
{
    /**
     * Count by criteria.
     *
     * TODO remove
     * @param array $criteria
     * @return int
     */
    public function countBy(array $criteria)
    {
        return $this->getEntityManager()->getUnitOfWork()->getEntityPersister($this->getEntityName())->count($criteria);
    }

    /**
     * Check if a community name exists.
     *
     * @param string $name
     * @return bool
     */
    public function checkIfNameExists(string $name) : bool
    {
        return $this->countBy(['name' => strtolower($name)]) > 0;
    }

    /**
     * Find community by exact name.
     *
     * @param string $name
     * @return Community
     * @throws NotFoundException If there is no communities with that name
     */
    public function findByName(string $name): Community
    {
        /** @var Community $community */
        $community = $this->findOneBy(['name' => $name]);

        if ($community === null) {
            $exception = new NotFoundException();
            $exception->addMessageWithCode(
                ErrorCodes::ENTITY_NOT_FOUND,
                'No existe una comunidad con ese nombre'
            );

            throw $exception;
        }

        return $community;
    }

    /**
     * Get all public communities.
     *
     * If a player is passed, retrieve all public communities to which player is not a member.
     *
     * @param Player $player
     * @return Community[]
     */
    public function getAllPublicCommunities(Player $player = null) : array
    {
        if ($player === null) {
            /** @var Community[] $communities */
            $communities = $this->findBy(['private' === false]);
            //$communities = R::find(static::ENTITY, 'private = 0 ORDER BY name ASC');

        } else {
            /** @var Community[] $communities */
            $qb = $this->getEntityManager()->createQuery(
                'SELECT c FROM AppBundle:Community c
                  WHERE c.private = 0
                    AND c.id NOT IN (SELECT com.id
                                       FROM AppBundle:Participant p
                                       JOIN p.community com
                                       JOIN p.player pl
                                      WHERE pl.id = :player_id
                                       
                    )'
            )->setParameter('player', $player->getId());

            $communities = $qb->getResult();
        }

        return $communities;
    }

    /**
     * Retrieve a random community.
     *
     * If a player is passed, retrieve random community to which player is not member.
     *
     * @param Player|null $player
     * @return Community
     */
    public function getRandomCommunity(Player $player = null): Community
    {

    }
}
