<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Community;
use AppBundle\Entity\GeneralClassification;
use AppBundle\Entity\Matchday;
use Doctrine\ORM\EntityRepository;

/**
 * GeneralClassificationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralClassificationRepository extends EntityRepository
{
    /**
     * Find classification for community.
     *
     * @param Community $community
     * @return GeneralClassification[]
     */
    public function findByCommunity(Community $community): array
    {

    }

    /**
     * Find classifications for community only until next matchday (or actual).
     * If a date is passed, only modified records after that date are returned.
     *
     * @param Community $community
     * @param Matchday $nextMatchday
     * @param \DateTime|null $date
     * @return array
     */
    public function findByCommunityUntilNextMatchdayModifiedAfterDate(
        Community $community,
        Matchday $nextMatchday,
        \DateTime $date = null
    ): array
    {

    }

    /**
     * Return classification for one community and one matchday.
     *
     * @param Matchday $matchday
     * @param Community $community
     * @return GeneralClassification[]
     */
    public function findOrderedByMatchdayAndCommunity(
        Matchday $matchday,
        Community $community
    ): array
    {

    }

    /**
     * Return ids of matchdays with general classifications registers updated after date.
     *
     * @param Community $community
     * @param \DateTime $date
     * @return array
     */
    public function findMatchdaysIdsWithGeneralClassificationUpdatedAfterDate(
        Community $community,
        \DateTime $date = null
    ): array
    {
        
    }
}
