<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MatchdayRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchdayRepository extends EntityRepository
{
}
