<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    /**
     * Checks if nickname exists.
     * @param string $nickname
     * @return bool
     */
    public function checkNickameExists(string $nickname) : bool
    {

    }

    /**
     * Check if email exists.
     * @param string $email
     * @return bool
     */
    public function checkEmailExists(string $email) : bool
    {

    }

    /**
     * Find player by nickname or email.
     * @param string $name
     * @return PlayerInterface Player.
     * @throws NotFoundException Player not found.
     */
    public function findPlayerByNicknameOrEmail(string $name) : PlayerInterface
    {

    }

    /**
     * @param string $token
     * @return PlayerInterface Player.
     * @throws NotFoundException
     * @throws \Exception
     */
    public function findPlayerByToken(string $token) : PlayerInterface
    {

    }
}
