imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: admin/design.yml }
#    - { resource: admin/ }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.images: /uploads/images
    app.path.user_contracts: /uploads/files/user/contracts

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        url: '%database_url%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# File Uploader
vich_uploader:
    db_driver: orm
    mappings:
        images:
            uri_prefix: '%app.path.images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images'

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address:        noreply@example.com
        sender_name:    Demo App

fos_rest:
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json ], fallback_format: json, prefer_extension: true }
            - { path: ^/, stop: true }

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

easy_admin:
    design:
        form_theme: horizontal
        menu:
            - { label: Players }
            - { entity: Player, icon: user }
            - Token
            - Community
            - Participant
            - { label: Matchday }
            - Competition
            - Phase
            - Matchday
            - Match
            - { label: Classifications }
            - Forecast
            - MatchdayClassification
            - GeneralClassification
            - { label: Teams data }
            - Team
            - Stadium
            - { label: Users }
            - User
            - { label: Other }
            - Image
    entities:
        Community:
            class: AppBundle\Entity\Community
        Competition:
            class: AppBundle\Entity\Competition
        Forecast:
            class: AppBundle\Entity\Forecast
        GeneralClassification:
            class: AppBundle\Entity\GeneralClassification
        Image:
            class: AppBundle\Entity\Image
            form:
                list:
                    actions:
                        - { name: 'show', label: '', icon: 'search' }
                        - { name: 'edit', label: '', icon: 'edit' }
                        - { name: 'delete', label: '', icon: 'trash' }
                    fields:
                        - id
                        - imageType
                        - description
                        - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                fields:
                    - imageType
                    - description
                    - { property: 'imageFile', type: 'vich_image' }
        Match:
            class: AppBundle\Entity\Match
        Matchday:
            class: AppBundle\Entity\Matchday
        MatchdayClassification:
            class: AppBundle\Entity\MatchdayClassification
        Participant:
            class: AppBundle\Entity\Participant
        Phase:
            class: AppBundle\Entity\Phase
        Player:
            class: AppBundle\Entity\Player
        Stadium:
            class: AppBundle\Entity\Stadium
            list:
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - id
                    - name
                    - city
                    - { property: 'stadiumImage', type: 'image', base_path: '%app.path.images%' }
            show:
                fields:
                    - id
                    - name
                    - city
                    - { property: 'stadiumImage', type: 'image', base_path: '%app.path.images%' }
            form:
                fields:
                    - name
                    - city
                    - image
        Team:
            class: AppBundle\Entity\Team
        Token:
            class: AppBundle\Entity\Token
        User:
            class: AppBundle\Entity\User

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations